[package]
name = "nixblitzlib"
version = "0.1.0"
edition = "2021"
license = "MIT"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
garde = { version = "0.18.0", features = ["full"] }
serde = { version = "1.0.199", features = ["derive"] }
toml = "0.8.12"

# crates.io version is out of date
# https://github.com/kamadorueda/alejandra/issues/406
alejandra = { git = "https://github.com/kamadorueda/alejandra" }
include_dir = { version = "0.7.4", features = ["glob"] }
handlebars = "6.1.0"
error-stack = "0.5.0"
thiserror = "1.0.63"
sha-crypt = "0.5.0"
serde_json = "1.0.128"
once_cell = "1.20.2"
strum = "0.26.3"
strum_macros = "0.26.4"

[dev-dependencies]
tempdir = "0.3.7"
tempfile = "3.12.0"
