set positional-arguments

default:
	just --list

# Build the current configuration (args: nixos-vm, pi-image)
build target="nixos-vm":
	#!/usr/bin/env bash
	if [[ "{{target}}" == "nixos-vm" ]] ; then
		cd src && nixos-rebuild build-vm --flake .#nixblitzx86vm
	elif [[ "{{target}}" == "pi4-image" ]] ; then
		cd src && nix build .#images.pi4
	elif [[ "{{target}}" == "pi5-image" ]] ; then
		cd src && nix build .#images.pi5
	else
		echo "Invalid environment. Please specify 'production' or 'staging'."
	fi

# runs the current qemu vm
vm-run:
  bash ./dev_scripts/run_vm.sh

# ssh into the currently running qemu vm
vm-ssh:
	ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no admin@localhost -p 10022

# sync the source to the remote vm from current directory
vm-sync-src:
  rsync -rvz --exclude .git/ --exclude nixblitzvm.qcow2 --exclude src/result -e "ssh -p 10022 -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no" . admin@localhost:/home/admin/src

# resets the vm by deleting the tbnix_vm.qcow2 file
vm-reset:
	rm -i nixblitzvm.qcow2
