[package]
name = "nixblitz"
version = "0.1.0"
edition = "2021"
description = "A CLI interface to the RaspiBlitz project."
resolver = "2"

authors = ["fusion44 <some.fusion@gmail.com>"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.17", features = ["derive", "cargo", "wrap_help", "unicode", "string", "unstable-styles"] }
config = {version = "0.14.0", features = ["toml"]}
crossterm = { version = "0.28.1", features = ["serde", "event-stream"] }
derive_deref = "1.1.1"
directories = "5.0.1"
futures = "0.3.30"
json5 = "0.4.1"
lazy_static = "1.5.0"
pretty_assertions = "1.4.0"
signal-hook = "0.3.17"
ratatui = { version = "0.29.0", features = ["serde", "macros"] }
ratatui-macros = "0.5.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.128"
strum = { version = "0.26.1", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = "0.7.12"
nixblitzlib = { path = "../nixblitzlib" }
tui-scrollview = "0.4.1"
tui-prompts = "0.4.1"
tui-popup = "0.5.1"
tui-textarea = "0.7.0"
error-stack = "0.5.0"
thiserror = "1.0.63"
cli-log = { version = "2.0.0", default-features = false }
indexmap = "2.7.0"

[build-dependencies]
vergen = { version = "8.2.6", features = [ "build", "git", "gitoxide", "cargo" ]}
